workspace = 1, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24, default:true
workspace = 2, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24
workspace = 3, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24
workspace = 4, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24
workspace = 5, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24
workspace = 6, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24
workspace = 7, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24
workspace = 8, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24
workspace = 9, monitor:desc:Dell Inc. DELL S2722QC 4CQWH24
workspace = 10, monitor:eDP-1, default:true

windowrule = match:class thunderbird, workspace 10 silent
windowrule = match:class slack, workspace 10 silent
